export const STUDENT_LIST_REQUEST =  'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS =  'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL';
export const ADD_COURSE_STUDENT_REQUEST =  'ADD_COURSE_STUDENT_REQUEST';
export const ADD_COURSE_STUDENT_SUCCESS =  'ADD_COURSE_STUDENT_SUCCESS';
export const ADD_COURSE_STUDENT_FAIL = 'ADD_COURSE_STUDENT_FAIL';
